### ISSUE TITLE
R dependencies not available

### ISSUE THREAD

**Issue by meflacava** [xinghuq/GenomeAdapt#1]
I tried to install this R package, but was unable to because the follow dependencies are not available (I'm working in R version 4.1.0): ‘qvalue’, ‘SNPRelate’, ‘gdsfmt’.

**Comment by xinghuq** [comment]
> 

Hi @meflacava , the dependences are not automatically installed from RCAN as they are available from , you can install these dependencies by:
 if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("qvalue")

Cheers,

**Comment by meflacava** [comment]
Thank you, that worked!
